#! /bin/sh

case $1 in
    start)
        echo "Loading aesd drivers"
        aesdchar_load
        ;;
    stop)
        echo "Stopping aesd drivers"
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0